application: khan-wiki-nl
version: 8
runtime: python27
api_version: 1
threadsafe: true

builtins:
- remote_api: on
- deferred: on

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^env
- ^tools
- ^gaewiki/khanlms/env
- ^gaewiki/khanlms/tools


handlers:
- url: /gae-wiki-static/
  static_dir: gaewiki/static
- url: /favicon.ico
  static_files: gaewiki/static/favicon.ico
  upload: gaewiki/static/favicon.ico
- url: .*
  script: gaewiki.application

libraries:
- name: django
  version: "1.3"
- name: jinja2                                                                  
  version: latest                                                               
- name: pycrypto
  version: latest
- name: markupsafe
  version: latest

#- url: /static/
#  static_dir: static
#- url: .*
#  script: handlers.py

